osx_image: xcode8
language: objective-c

xcode_sdk: iphonesimulator10.0

script:
- set -o pipefail && xcodebuild test -workspace Example/JWMediaManager.xcworkspace -scheme JWMediaManager-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
