language: objective-c
osx_image: xcode8.2

script:
  - cd Example
  - set -o pipefail && xcodebuild -workspace JWMediaManager.xcworkspace -scheme JWMediaManager-Example -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO | xcpretty
