language: objective-c

script:
  - cd Example
  - xcodebuild -version
  - xcodebuild -project
  # - set -o pipefail && xcodebuild -workspace JWMediaManager.xcworkspace -scheme JWMediaManager-Example -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO
